import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import Navbar from "@/components/navbar/navbar";
import React from "react";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import {StoreProvider} from "@/providers/StoreProvider";
import {Providers} from "@/providers/Providers";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="ru">
    <body className="layout-body">
    <Providers>
      <Header/>
      <main className="page">
        <Navbar/>
        {children}
      </main>
      <Footer/>
    </Providers>
    </body>
    </html>
  )
}
